# Generated by Django 4.0.4 on 2022-05-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='profile_img',
            field=models.ImageField(default='Blog\\static\x08lank-profile.png', upload_to=''),
        ),
    ]
