# Generated by Django 4.0.4 on 2022-05-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_blogger_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='interests',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogger',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blogger',
            name='skills',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
